### ISSUE TITLE
Classroom no longer exists ?

### ISSUE THREAD

**Issue by ShxttaSyko** [Losh531/repl-hackerplan#1]
Can't join the classroom.

**Comment by PeterParker00** [comment]
Yes same issue its saying this now!

There was an error accepting the assignment. Starter code template repository was not found. The repository might be deleted or the classroom's organization does not own the repository.. If this problem persists, please contact support

**Comment by Losh531** [comment]
Hey guys!
The repl promotion has ended so this will sadly no longer work :(
